// <auto-generated />
using System;
using FoodOrder.Pedidos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodOrder.Pedidos.Infrastructure.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    partial class PedidosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("numero_pedido_seq", "public");

            modelBuilder.Entity("FoodOrder.Pedidos.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('public.numero_pedido_seq')");

                    b.Property<int>("PagamentoStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoStatus")
                        .HasColumnType("integer");

                    b.Property<int>("SacolaId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TempoEspera")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("FoodOrder.Pedidos.Domain.Entities.Sacola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sacola");
                });

            modelBuilder.Entity("FoodOrder.Pedidos.Domain.Entities.SacolaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("SacolaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SacolasProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
