# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/FoodOrder.Pedidos.Presentation/FoodOrder.Pedidos.Presentation.csproj", "src/FoodOrder.Pedidos.Presentation/"]
COPY ["src/FoodOrder.Pedidos.Application/FoodOrder.Pedidos.Application.csproj", "src/FoodOrder.Pedidos.Application/"]
COPY ["src/FoodOrder.Pedidos.Domain/FoodOrder.Pedidos.Domain.csproj", "src/FoodOrder.Pedidos.Domain/"]
COPY ["src/FoodOrder.Pedidos.Infrastructure/FoodOrder.Pedidos.Infrastructure.csproj", "src/FoodOrder.Pedidos.Infrastructure/"]
RUN dotnet restore "./src/FoodOrder.Pedidos.Presentation/FoodOrder.Pedidos.Presentation.csproj"
COPY . .
WORKDIR "/src/src/FoodOrder.Pedidos.Presentation"
RUN dotnet build "./FoodOrder.Pedidos.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./FoodOrder.Pedidos.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FoodOrder.Pedidos.Presentation.dll"]