name: CI - Build e Testes

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: 🧪 Restaurar dependências
        run: dotnet restore FoodOrder.Pedidos/FoodOrder.Pedidos.sln

      - name: 🧱 Build do projeto
        run: dotnet build FoodOrder.Pedidos/FoodOrder.Pedidos.sln --no-restore --configuration Release

      - name: 🧪 Rodar testes
        run: dotnet test FoodOrder.Pedidos/FoodOrder.Pedidos.sln --no-build --verbosity normal
